name: "CI/CD do Nomad"

on:
  push:
    branches:
      - "fix/refactor_cicd"

env:
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY }}

jobs:
  plan:
    name: 'terraform plan'
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_KEY }}
          project_id: mentoria-iac-staging
          export_default_credentials: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        id: validate
        run: terraform validate
        continue-on-error: true

      - name: Terraform create new workspace
        id: workspace-test
        run: terraform workspace new test || terraform workspace select test

      - name: Terraform Plan
        id: plan
        run: terraform plan -var region=us-west1 -out="terraform_plan"

      - name: Terraform Apply
        id: apply
        run: terraform apply "terraform_plan"

      - name: Terraform Destroy
        id: destroy
        run: terraform destroy -auto-approve

      - name: Terraform create new workspace
        id: workspace-staging
        run: terraform workspace new staging || terraform workspace select staging

      - name: Terraform Plan
        id: plan-staging
        run: terraform plan -out="terraform_plan"



      

